# Generated by Django 3.1.7 on 2021-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210316_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=149, verbose_name='Title of Article'),
        ),
    ]
